services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blog_project_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "#subhankar123"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "bundle install && bundle exec rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: blog_project_development
      DB_USER: postgres
      DB_PASSWORD: "#subhankar123"

volumes:
  postgres_data:
