default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: '#subhankar123'
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: blog_project_development

test:
  <<: *default
  database: blog_project_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
